INSERT INTO alumno (id, nombre) VALUES (8, 'AGUILA ANGUIANO PABLO EFRAIN');
INSERT INTO alumno (id, nombre) VALUES (9, 'BRIONES BELTRAN EVELYN SARAHI');
INSERT INTO alumno (id, nombre) VALUES (10, 'BECERRA NAVARRO BARBARA ARIADNA');
INSERT INTO alumno (id, nombre) VALUES (11, 'BARAJAS GOMEZ VAIOLET SINNAI');
INSERT INTO alumno (id, nombre) VALUES (12, 'CANDELARIO YAÑEZ ANIELA GETZEMANI');
INSERT INTO alumno (id, nombre) VALUES (13, 'CASTELLANOS MARAVILLA LUIS ANGEL');
INSERT INTO alumno (id, nombre) VALUES (14, 'CERVANTES ROSALES ELLIOT EDURADO');
INSERT INTO alumno (id, nombre) VALUES (15, 'SEGURA CARRILLO GONZALO');
INSERT INTO alumno (id, nombre) VALUES (16, 'COLIMA MENDEZ SANTIAGO URIEL');
INSERT INTO alumno (id, nombre) VALUES (17, 'ESPINOZA OROZCO MAITE MONSERRAT');
INSERT INTO alumno (id, nombre) VALUES (18, 'DIAZ GUZMAN LUIS ALBERTO');
INSERT INTO alumno (id, nombre) VALUES (19, 'GALVAN ONTIVEROS VIRGINIA DEL CARMEN');
INSERT INTO alumno (id, nombre) VALUES (20, 'FLORES GONZALES IKER DARIO');
INSERT INTO alumno (id, nombre) VALUES (21, 'GUTIERREZ HERNANDEZ MANUEL ANTONIO');
INSERT INTO alumno (id, nombre) VALUES (22, 'GARCIA FLORES FERNANDO MISSAEL');
INSERT INTO alumno (id, nombre) VALUES (23, 'GOMEZ SIMENTAL MIRANDA DENISSE');
INSERT INTO alumno (id, nombre) VALUES (24, 'HERNANDEZ FRANCO ANGELICA FERNANDA');
INSERT INTO alumno (id, nombre) VALUES (25, 'HERNANDEZ MENDOZA CESAR JESUS');
INSERT INTO alumno (id, nombre) VALUES (26, 'HERNANDEZ GONZALES KENYA YAMILET');
INSERT INTO alumno (id, nombre) VALUES (27, 'OLIVARES MERCADO BRUNO ALEXANDER');
INSERT INTO alumno (id, nombre) VALUES (28, 'JIMENEZ CALDERON DORIAN ANTONIO');
INSERT INTO alumno (id, nombre) VALUES (29, 'MACIAS LUNA CRISTOPHER LEONEL');
INSERT INTO alumno (id, nombre) VALUES (30, 'PLASCENCIA FLORES JESUS ALEJANDRO');
INSERT INTO alumno (id, nombre) VALUES (31, 'REYES MENDEZ BRANDON OMAR');
INSERT INTO alumno (id, nombre) VALUES (32, 'MERCADO MUÑOZ MONICA JACQUELINE');
INSERT INTO alumno (id, nombre) VALUES (33, 'RUELAS SANCHEZ XIMENA');
INSERT INTO alumno (id, nombre) VALUES (34, 'ROMERO ESTRADA LIZBETH GUADALUPE');
INSERT INTO alumno (id, nombre) VALUES (35, 'RIVERA ESPINOZA MELANIE VANESSA');
INSERT INTO alumno (id, nombre) VALUES (36, 'RODRIGUEZ MARTINEZ MELISIA ROMINA');
INSERT INTO alumno (id, nombre) VALUES (37, 'TEJEDA MALDONADO ROMINA LIZETH');
INSERT INTO alumno (id, nombre) VALUES (38, 'SEPULVEDA BRAVO ANGEL AARON');
INSERT INTO alumno (id, nombre) VALUES (39, 'ZAMBRANO ARGUELLES KAROL BENILEY');
INSERT INTO alumno (id, nombre) VALUES (40, 'TORRES MARTINEZ GIANCARLO ALEXANDER');

INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 15, 11, 2);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 15, 14, 13);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 15, 21, 7);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 15, 22, 6);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 15, 20, 9);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 15, 38, 3);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 15, 15, 5);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 15, 16, 13);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 15, 18, 10);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 15, 27, 10);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 15, 13, 4);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 15, 23, 14);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 15, 36, 1);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 15, 34, 5);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 15, 25, 10);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 14, 12, 0);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 14, 32, 4);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 14, 14, 2);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 14, 31, 11);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 14, 23, 1);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 14, 9, 0);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 14, 28, 11);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 14, 13, 0);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 14, 21, 12);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 14, 39, 0);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 14, 33, 7);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 14, 17, 9);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 14, 37, 0);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 14, 15, 12);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1100, 14, 38, 7);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1010, 15, 25, 5);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1010, 15, 13, 8);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1010, 15, 15, 12);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1010, 15, 10, 9);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1010, 15, 40, 12);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1010, 15, 38, 2);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1010, 15, 36, 3);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1010, 15, 14, 11);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1010, 15, 32, 4);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1010, 15, 17, 6);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1010, 15, 26, 0);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1010, 15, 11, 6);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1010, 15, 39, 5);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1010, 15, 28, 3);
INSERT INTO alumno_grupo (materia_clave, grupo_seccion, alumno_id, asistencias) VALUES (1010, 15, 22, 7);

